# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
defaults: &defaults
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  signing_key: <%= ENV["SIGNING_KEY"] %>
  basic_auth:
    username: <%= ENV['BASIC_AUTH_USERNAME'] %>
    password: <%= ENV['BASIC_AUTH_PASSWORD'] %>
  france_connect_particulier:
    identifier: <%= ENV['FC_PARTICULIER_ID'] %>
    secret: <%= ENV['FC_PARTICULIER_SECRET'] %>
    redirect_uri: https://<%= ENV['APP_HOST'] %>/france_connect/particulier/callback
    authorization_endpoint: <%= ENV['FC_PARTICULIER_BASE_URL'] %>/api/v1/authorize
    token_endpoint: <%= ENV['FC_PARTICULIER_BASE_URL'] %>/api/v1/token
    userinfo_endpoint: <%= ENV['FC_PARTICULIER_BASE_URL'] %>/api/v1/userinfo
    logout_endpoint: <%= ENV['FC_PARTICULIER_BASE_URL'] %>/api/v1/logout
  github:
    client_id: <%= ENV['GITHUB_CLIENT_ID'] %>
    client_secret: <%= ENV['GITHUB_CLIENT_SECRET'] %>
  mailjet:
    api_key: <%= ENV['MAILJET_API_KEY'] %>
    secret_key: <%= ENV['MAILJET_SECRET_KEY'] %>
  api_entreprise:
    key: <%= ENV['API_ENTREPRISE_KEY'] %>
  pipedrive:
    key: <%= ENV['PIPEDRIVE_KEY'] %>
  fog:
    openstack_tenant: <%= ENV['FOG_OPENSTACK_TENANT'] %>
    openstack_api_key: <%= ENV['FOG_OPENSTACK_API_KEY'] %>
    openstack_username: <%= ENV['FOG_OPENSTACK_USERNAME'] %>
    openstack_auth_url: <%= ENV['FOG_OPENSTACK_AUTH_URL'] %>
    openstack_region: <%= ENV['FOG_OPENSTACK_REGION'] %>
    directory: <%= ENV['FOG_DIRECTORY'] %>
  carrierwave:
      cache_dir: <%= ENV['CARRIERWAVE_CACHE_DIR'] %>
  mailtrap:
    username: <%= ENV['MAILTRAP_USERNAME'] %>
    password: <%= ENV['MAILTRAP_PASSWORD'] %>
  helpscout:
    mailbox_id: <%= ENV['HELPSCOUT_MAILBOX_ID'] %>
    client_id: <%= ENV['HELPSCOUT_CLIENT_ID'] %>
    client_secret: <%= ENV['HELPSCOUT_CLIENT_SECRET'] %>
    webhook_secret: <%= ENV['HELPSCOUT_WEBHOOK_SECRET'] %>

development:
  <<: *defaults

test:
  <<: *defaults

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *defaults
